library(rvest)

teamList <- list(
  'air-force',
  'akron',
  'alabama',
  'appalachian-state',
  'arizona',
  'arizona-state',
  'arkansas',
  'arkansas-state',
  'army',
  'auburn',
  'ball-state',
  'baylor',
  'boise-state',
  'boston-college',
  'bowling-green-state',
  'buffalo',
  'byu',
  'california',
  'central-michigan',
  'charlotte',
  'cincinnati',
  'clemson',
  'coastal-carolina',
  'colorado',
  'colorado-state',
  'connecticut',
  'duke',
  'east-carolina',
  'eastern-michigan',
  'florida',
  'florida-atlantic',
  'florida-international',
  'florida-state',
  'fresno-state',
  'georgia',
  'georgia-southern',
  'georgia-state',
  'georgia-tech',
  'hawaii',
  'houston',
  'illinois',
  'indiana',
  'iowa',
  'iowa-state',
  'kansas',
  'kansas-state',
  'kent-state',
  'kentucky',
  'liberty',
  'louisiana',
  'louisiana-tech',
  'louisiana-monroe',
  'louisville',
  'lsu',
  'marshall',
  'maryland',
  'massachusetts',
  'memphis',
  'miami-fl',
  'miami-oh',
  'michigan',
  'michigan-state',
  'middle-tennessee-state',
  'minnesota',
  'mississippi-state',
  'missouri',
  'navy',
  'nebraska',
  'nevada',
  'nevada-las-vegas',
  'new-mexico',
  'new-mexico-state',
  'north-carolina',
  'north-carolina-state',
  'north-texas',
  'northern-illinois',
  'northwestern',
  'notre-dame',
  'ohio',
  'ohio-state',
  'oklahoma',
  'oklahoma-state',
  'old-dominion',
  'ole-miss',
  'oregon',
  'oregon-state',
  'penn-state',
  'pitt',
  'purdue',
  'rice',
  'rutgers',
  'san-diego-state',
  'san-jose-state',
  'smu',
  'south-alabama',
  'south-carolina',
  'south-florida',
  'southern-mississippi',
  'stanford',
  'syracuse',
  'temple',
  'tennessee',
  'texas',
  'texas-a&m',
  'texas-christian',
  'texas-state',
  'texas-tech',
  'toledo',
  'troy',
  'tulane',
  'tulsa',
  'uab',
  'ucf',
  'ucla',
  'usc',
  'utah',
  'utah-state',
  'utep',
  'utsa',
  'vanderbilt',
  'virginia',
  'virginia-tech',
  'wake-forest',
  'washington',
  'washington-state',
  'west-virginia',
  'western-kentucky',
  'western-michigan',
  'wisconsin',
  'wyoming'
)

team <- teamList[[x]]
  
teamLog <- function(team) {
  url <- read_html(paste0("https://www.sports-reference.com/cfb/schools/", team, "/2019/gamelog/"))
  file <- paste0("offense", team, "2019.csv")
  table <- url %>%
    html_nodes("table") %>%
    .[1] %>%
    html_table(fill = TRUE)
  write.csv(table, file=file)  
}

lapply(teamList, teamLog)
